version: "3"
services:
  hub:
    image: selenium/hub
    container_name: web-automation_hub
    ports:
      - "4444:4444"
    environment:
      GRID_MAX_SESSION: 10
      GRID_BROWSER_TIMEOUT: 3000
      GRID_TIMEOUT: 3000
    networks:
      - selenium_grid_internal

  chrome:
    image: selenium/node-chrome
    container_name: web-automation_chrome
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 5
      NODE_MAX_INSTANCES: 5
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "9001:5900"
    networks:
      - selenium_grid_internal

  firefox:
    image: selenium/node-firefox
    container_name: web-automation_firefox
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 5
      NODE_MAX_INSTANCES: 5
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "9002:5900"
    networks:
      - selenium_grid_internal
networks:
  selenium_grid_internal: